env:
  global:
    - secure: nNGqL1WHNpdct0Bh2FzPXrEA7Psf/zTA1HQ0GPzjddU4HiSStjWuESOX5JbPnd/m3x9jLweH7N9UCkcLMNsQKs7m1uoMWIU8keTcOemUuNvPmM5S9BIJJoKhk1z1OQSKrdZLe7Jr/fPkyKLaFrwRse2w7bAm4wdn0uhuvrVwfv/3Gf3sKm1DZfK6l2iYnLaiJEe4ggLTJ9LYKy1m95mFWVhz0o5QkafOHXyJUX7KTQbblI9yCc+xSHxyG5oNw9j025rBCJcW9sgkOnjZ4Mrcy8AbUx8Bg+Hq+oWGy0qpkR8WFLcNx//ht90mdMaj81OBtOu9QcfL2aLW6/4G8Gyhd42Tn7q8Cfb6ZJTakroRdhwjWBYk+m9wlRtmUUlVqFu6IT/rT4HXfwrKuikMcQN8YSbnhrjpmIcD15vWQ42BAFQ5wopHdOWoTrTo7ZmR2y/YV/qOp9b08V+OxQojqKU8VsgoYAPhGbIusbcZXf0avuYt/0nrAq4hdV9Yw6Ak5EeH6s47QFkURL4vTz2jTTEb5qEyAaH+dbvgiBkNJL+zKW5pj6dAsA4I3NcDU/4H3FQ6UTyDCkkeNcdCsZWbL4f2/9K06VD/iVv2gumVXYNYD6YS40DZwB154k8jW0fxsBRH/6efyPr3sgQv4JyetOOpLwi9iPDFsm28jPXKsXaZVj0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
