env:
  global:
    - secure: MK74ZZdbUW/C7K9BZyao7lFE9R49kV9zlP6YrJ2hI81M3cD48u0w57BOZzZkBuLMp+kh+bqlen6sQJPrOYDoelwHv2a51n60nrH6F5aHgP6p70PS+GJDcl6Hhie2rweUGEsgl7SnDnMozbxe5bajbXcq2x/UMLp0von8Hoq0vS+AbRDGTRX3OA+05qrTw1l06qzU4optLF4xengQyJxLsAl0hTxG/7f8YiqbBXfzm3ydFTkXTH9sip4KFwfm0SUx2BEazZmFWK2aSG/PNq/PD6vR/X6eyiDMhXq/kqc6k53Ejox4VtM0Sly2VVtzRdzdgCjACEqvs1KUTOlHroKmIXuvy8QaaUdWoVFl3NFlrf6Uxf/F5624koXlBi5ItB1LEDX8GLWR9XsZsZZpF4astmO+evjs9p3b3LDhLwy5Th4LVz9IGLQGcDBwYysyvKOkG7dKru7XtCJ4ubJkjyANN/62Sk1eYkQZ71V5m2XuH8Zyor0mm+F2cU6J2Xe3OEehpE2TJ5acf6W2k8/8Vyu90KHmVKtXbrfk0oWN8ewD6Kae3twQTP95rc+GxmPnTNTuRqZ3vFCwTLSLu52YlLNNjT9u1pSq+d4rhmbOG6juv1qBm4PqK8vldyKC6iMR29rJ1UK/3EuSyBrB4aB8sHK0kKjtx9NR9H1JNqCPCMSIDUQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
