env:
  global:
    - secure: jwK4ABCAIszRw7PN9VUkdgndRjte3ZjIblEGjngt1DG1nIj8ho1aoRXNP0sYOkdV9QB/SQyPYDzsPVivn2sQ18YhL722R/7kDqKPGlcMtpt6pECtqAA2MCdLkI/BWIeZ3pezZESKKJhDHeysJI2n2XZzfDQJPdgnpqCU6ofkGw28ZcwCxruObUZi0dEx4L45gegSqQ+MZ9MnzfUne8WJleCKqx7xhJgm2d+sP9cOF1NyEYlmwTvWXjx9D109Ru/Bylz6u3xGQ7oOxseRyd0SF1A/R/s3/lOLuD60ZAf5bCM6mlUe4nUx1yXB9DHwq/fLuyXjdvJkOhAWEI6GjltZGztD4MXRtnGNu60uZY+zKZx7PfeQsaxTa1Z1ME+Xt+ZlLRR/7Z4m/3Ns2Xg2+s9esxuYiNBpNeZfHj7AgP/Ocy3YCz5n6xTFsNoPxGN3ZJbG4BLKGNfp5zKezTTKFXAptswwfb46JROEhWIFJ3msnkMePJCfCvdOg61mdsuTgl5liE3ZEv9E1QK8Fu4yZ0Or7i77GO/uwLWy/GexxCE7Xhgy2ZjpMnNTXsF4ONIP3rESinE/019uuvh1RHnj/Siqrc4XQ5KCvW7Yy96Hj2gUrLIsCB17tmOcR8p+dd7J1xD5m560G2AE0LCRuFbOVf97V7gVe8XGoQS7047NsLY7sf8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
