env:
  global:
    - secure: obMZVjJTUu3FAIJ6fKwepn5sGEJmuh3o7Bi2GRiIfXMMQxTCxoUiCKYdj5jLi5i3Xm0ZAdQMfXobGIrYxffTN8FeqaG3T6VjahAYSbgyI/qr6u3wco6ird8ZrtiIzS0U7t9zUozc29Y8WdjG9mwi3KVdFUSkXFhbPXhJ+sjn+Cq4xAs4jkT7OAYlaKkjCdXMSdbowHdu6EFOHyCBrpS3YxDCekcDwAtqmSnm8UF77Nd4yQbqg15RffYLLVgSf1iTtbmbZlTg4DAVk/otZmpc6ggMcvX3jUJSopAMv9VBLh9aQKYCyGGy64AluC6ztgprPT0omB/0vrrHDL2EHF275HfkRpycQuTqqZi8qVp6NZRyvVCbUxKxBehKV+QrkA8iOfIRR/qNDOweQuoaJikQhVC6moVNaKdgV4ticfU30rst8K2hKhP3HmCLaxcqjgxJfhqIWFwKN+wNLr02ZVzhsWYJ2QFFAmmZLpFVPtHr61kqm9Tt6EDG59ypNTSdZdBFixiHXDDg4EdFCxF3mqJr3pwBiJjFu1aN3wU4KIPFKkqOXb1CE/nio2nJfBnMbRE7/1KIB4InYljFviXcSb/uAOIOrrFf7yltU9dQbPi9GGEn8VGI2qEytSnF/TsZTJPsIH608t6fsF2fEFzSxrrenjvINRmmT7D76Bt5M3JVukQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
