env:
  global:
    - secure: TItx5+mT+04TTrwUaOqanKnqYzluiBeH0ZSxLggZzKt3VRJNBxKkY9oFH5wb2RSddjLNpLV63E5lW4jiNm/qK0b1p2AuEvbF89ILO9itJBpBkQ/iE0QlHBsMXaZbHnIVmkzB3Mx1be1gjNygO3GZBDC4aMCYF7A6DqeQUGkKH7IGsJ+a4qRYav4opzaT0jBjlNI5X4/tyNRku05ewSXupazxI9xHf9H0mOWCzN4MhFWbidwVUk7SYtwjCC//ZQOc7piVn09MGKvP6guHy+k5KX511+jD2r4MmqS4k7xEemx3wH+eP5UG8lYCPaE6JRVafC0gJJG2RWBdeNxCMui4ZTOgcg14YfDnVmwyiBsGegM387EyWNshCqErNiZfJyzlQIQSs3XWdcWNG3LgTS8v4Ti902pu9uLzaKg54t9dsMKNJKwYdS2OJzUSVwmCaPTrysgHPoJM59NxQhq1Q1adieaX/hMJoKSz7Smd2OEejKZKf0zvnw7VKVpx4neHx9BZpLIMKq4kfkw+vHIjcTZK5ZX/7+9V4hde6Tdgs8Px8q+1RGcsMDCWl3/A+4JT1MOx0Lc6dupr+TP/wnJmEXl3gSOwbBkHyT16TW7mhvZYbjrdRFr2i/sZ9osvjfSDDso2EpIt+mtrC6R6i1xRFamTGOnTicvXNc2ESJK2wJzjR0E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
