env:
  global:
    - secure: WwydxJO97AsCY78tv5Kj6rj0dMZCiw9hv/xgmbIiWOnZ3S3mKI8TvvjUWIZJtr+AONcixwhPMdaCNxwZEdKteLMaH5g8Dq6G4WU5IcjPWJPwDtdi/Xli+1GgF7o7cUCZSV6D0Fa2v7Z+wH0WNG0Hj/jZDwvNATP1FPiSMNJBRw+4ezs064+kMkFx/70iz3ZJIs40wwKb7UrZ9rTa9yB0nRMcZ+b6XyA+lzWKsR0ZCVy88aVwY+XXAQlQUAI5sfZ9F9dqBmBIOa3vOrbI9/0TsOoxT46Pr4XwkmaaFx2sJ4yoc3l5QIO0ss+aW3PSTLa05Ekz92zNJ8YqKw1riAIsasY3zNgXr/j6etlxBwhRYGoiGW9Iz/4YQcylssZzQpI9MHklq7eW2AzWwbkG/TEzrDbmWYRrCzSO2Y36OCbNIeWHo9xS7tVHdR0ksHnLj2TAZwYTHVVBY17nh6PZ56Y1QMI9jMwsbye4x5Fcq3ADXW5xEU5lmp2rCvyNvh0pJalNYvZnlh2sy9PMlqCihd67/Ok+LOip7vzdUX+SKfRFKM+4vxrla/py7Y1UKtbSEsVNZWibnOvAys9yx4fEKcxomw2t2Mafm9Q2dw77OwaVeStbIWR5wcIYKUvcb5yMo6TnKb4oct1x5X49jVczvDlBgN/CWil93IyGaeF96fPKagc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
