env:
  global:
    - secure: Y7HyOice6hBxXf7AMvWKOdVtYr7GNnv5FfyoULrSVfqJPrDrA9DP+/XW7Bt8V48ieM/bgFuWlkXwZ8Ie9/fLyoA7RsbkIn49nQasqnqU+Bkryxk+fHRAJwerIHRBwyaxLOsGJDfW5JfsUD8wZUMnVUCtJaNJlHLWKvzhSqhPGjy1r1nkBL1fc4Tnerv8pXDuMPA6v5LpK34tU6/S6573N+otksRH0A1I+zGYMqwF4q4WD7xu+/JCiqfrmiXFVqYlKxm2JQtJv5EvVO7ekX9TFUgUAfGhypAg0blqSQDhbb7VX9ewqPznqtHbKaDZa6IkBNacMFroZzqq+Bei3UVrQWJ+5H7zG3kzMwA+62bOa9hbU48GnR8Zzev/AQN3NxQyqMGZp9KZb5jFtM7TBwHu2Sgjassrz1UrT5cfCZ5v/p2KBwRZ08U0c5d/XYzg6motzC0461kqfN+BGd0XJkYYfa4jqfsqObTi3NiKMh/x3S15XUbX43wcIgL4S2LST9NS7T1aofeWRB/vaimmh/z21UP7htmI52U6aelz6G1cwgqDWXPh4DFbO2ham68OBYe431Mqrcx9q/PqAmTewnn+cWWu9ePthcGpyvl4sAZpWBetVayf6bYnU/4qgzJDTBbqLbWaZpjaN6GD3dtqJNgCinYjpcUUgZyO6n55OnAiHsk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
