env:
  global:
    - secure: JeArp6Sre/wJCgXaCRGlCJAir4IUn7txzgkSeD1lROwD5w9jtHqVwVeqPROAHPePfwF/56kJAkEYIfRZAoliGKJHgtcDwGxkelbBitNZFyV/WBKQfh8dF7pM1hsQu+U3SfKsQ7xQC/29bCZab6MtEeRXAJI4POOmayQEEIxDqpkBOtaI29DqprrRdDa+fR3H2GEmA8/92XTurARD68NldQfPRFWQJLfw705QkqR6xZeNSJjmmIBHA/Dd7Ugw9xOXj3VQT+SZsda99AWfRzcxKRo1QH0uDSnB98Yk0Z0igF3r4UWl1ZPJZE4xXJkWnAsLT8wMfh6md1pc0p5V0pcbCXmW/GXO+ySPd3A62BlYVFkrCEa0dXpVJUyEK2LbDuQoRVNaNelfkEJy3W+tJCh3vVlHGUY51LJQSRFSDBduG1jKtaWKLKmszADPRaRKtVezd2e4i1jgLHba5kjanefzX6KRhV19/ETLrDOGR1Yh1aOexrO2H39QTL6oC9FciMgcwjVQNaHCMpe+EIFSkfBcWM5qEfnkrjlse/nq5dSeFqxViVHsPYjglqUQD9284xhD/5GKDisVdoY6iN6n4mJPQEMg1PkyfZt4I2oDUMuNWCAeQGELgtYZkuAnDzqIcE1SAIv4gDd73FBr8akku7LGP6VF3DcE5JeTuEodSeOPNzo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
