env:
  global:
    - secure: kiEG57G66TjObZqSxcbF7e4VZmFR1wxN5MqcEVs3b30BALtJkQl8yaxYTgCv21+087h+ijzn4Z0wamqd9X8evyONzjojZLz6ozQx9IA4RAK3ItZHN1ssSoNOudvpioUbBvU/4QNWaZDpLqwNxXPtm/7ZYz/tBfVXB5qleLtcOAPP25X8+U47A6Oom+DhiH+dSQZqwQM17/eg/uywpiNDQe15F52kXOvqUBmc0MOQ9w5cCTBPJHDaT9ExrnstkHaopPTwLL/9r6B4O+CbHOTLAibunqLsE/yTIPXAkzJRy/ii8yvisX1cGgbi6fD/df4aiieQae8UoKfiJ2fp3TDBlwVmLdZp2o/PGXZILVb17HABjrkZcllxVleXcDhMDamA1woweBz+67hUJtHQx3At358Co8d1BCKaFSpNB0KkFbLugvpKJAmc4vZrPlnCCyYZ4euNAmBtB8leRJKHlLn5LX/KcZqCAV/AP9taPVBbAXH2kBbhmvQH7QcOMxKLW4Z7IGSpu7QHW6l1Rfjhg71gPqmnNLVw7pEerc3sc5nZFcw7gkj9f/CHgYmc2n1eS5K7KZn+OnotHmBrzjTqdpKszs3bBgVDb8WCveB2w+9MRaGz5z5SRbfZF3qdAIkkMDPBuhxdgb8QdaTNMGteUnnGe0M5CVtayOZxscub3fykko4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
